<?php

namespace Drupal\webform_strawberryfield\Element;

use Drupal\webform\Element\WebformManagedFileBase;

/**
 * Provides a webform element for an 'file' element to be uploaded via tus.
 *
 * @FormElement("webform_tus_file")
 */
class WebformTusFile extends WebformManagedFileBase {

  public function getInfo() {
		$info = parent::getInfo();
		unset($info['#attached']);
    return $info; // TODO: Change the autogenerated stub
  }


}
